# Generated by Django 4.1.2 on 2022-10-17 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barcos_anfibio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_barco', models.CharField(default='', max_length=64)),
                ('codigo_barco', models.CharField(default='', max_length=32)),
                ('ruta_foto', models.CharField(default='', max_length=64)),
                ('fabricante_barco', models.CharField(default='', max_length=64)),
                ('ubicacion', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='img_anfibio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_img', models.CharField(default='', max_length=64)),
                ('codigo_img', models.CharField(default='', max_length=64)),
                ('res_img', models.CharField(default='', max_length=64)),
                ('fecha_img', models.DateField(default=datetime.date.today)),
                ('peso_img', models.CharField(default='', max_length=64)),
                ('codigo_operacion', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='operacion_anfibio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField(default=datetime.date.today)),
                ('distancia_operacion', models.CharField(default='', max_length=64)),
                ('duracion_operacion', models.CharField(default='', max_length=64)),
                ('codigo_embarcacion', models.CharField(default='', max_length=64)),
                ('codigo_usuario', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='usr_anfibio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=64)),
                ('apellido', models.CharField(default='', max_length=64)),
                ('rol_usr', models.CharField(default='', max_length=32)),
                ('codigo_usr', models.CharField(default='', max_length=32)),
                ('nro_celular', models.CharField(default='', max_length=32)),
                ('email_usr', models.CharField(default='', max_length=64)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('cod_verificacion', models.CharField(default='', max_length=64)),
                ('usr_password', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='video_anfibio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_video', models.CharField(default='', max_length=64)),
                ('codigo_video', models.CharField(default='', max_length=64)),
                ('res_video', models.CharField(default='', max_length=64)),
                ('fecha_video', models.DateField(default=datetime.date.today)),
                ('duracion_video', models.CharField(default='', max_length=64)),
                ('peso_video', models.CharField(default='', max_length=64)),
                ('codigo_operacion', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
